#!/usr/bin/env bash
# simple single line system statistics

UPTIME="$(uptime)"

UP=$(echo "$UPTIME" | \
awk '{
  sub(/.*up[ ]+/,"",$0)
  sub(/,[ ]+[0-9]+ user.*/,"",$0)
  sub(/,/,"",$0)
  print($0)
}')
MSG="uptime: $(tput setaf 4)$UP$(tput sgr0)"



if [ "$(uname)" = "Darwin" ]; then
  BATTERY_CHARGE=$(pmset -g ps | sed -n 's/.*[[:blank:]]+*\(.*%\).*/\1/p')

  BATTERY_MAX=$(ioreg -w0 -l | grep MaxCapacity | cut -d '=' -f2)
  BATTERY_DESIGN=$(ioreg -w0 -l | grep DesignCapacity | cut -d '=' -f2)
  BATTERY_CYCLES=$(ioreg -w0 -l | grep CycleCount | cut -d '=' -f2 | grep [1-9])

  BATTERY_HEALTH=$(echo "scale=2; $BATTERY_MAX / $BATTERY_DESIGN * 100" | bc | sed "s/\..*//g")

  if [ "$BATTERY" != "100%" ]; then
    MSG="$MSG, battery charge: $(tput setaf 3)$BATTERY_CHARGE$(tput sgr0)"
    MSG="$MSG, battery health: $(tput setaf 3)$BATTERY_HEALTH%$(tput sgr0)"
    MSG="$MSG, battery cycles: $(tput setaf 3)$BATTERY_CYCLES$(tput sgr0)"

  fi
fi

echo "$MSG"
